-- Seed usuarios desde Supabase Auth primero. Luego reemplaza los UUID por perfiles reales.
-- insert into public.barberias (nombre, direccion, admin_id)
-- values ('Barberia Central', 'Calle principal #123', '<admin-profile-id>');
